;;; .user-lisp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from doxygen.el

(register-definition-prefixes "doxygen" '("doxygen-" "my/split-string"))


;;; Generated autoloads from eglot-signature-eldoc-talkative.el

(register-definition-prefixes "eglot-signature-eldoc-talkative" '("eglot-signature-eldoc-talkative"))


;;; Generated autoloads from emacs-pager.el

(autoload 'emacs-pager-mode "emacs-pager"
"Mode for viewing data pagd by `emacs-pager`.

This mode runs the hook `emacs-pager-mode-hook', as the final or
penultimate step during initialization.

\\{emacs-pager-mode-map}" t)
(autoload 'emacs-pager "emacs-pager"
"Show contents of file at PATH.

(fn PATH)")
(register-definition-prefixes "emacs-pager" '("emacs-pager-"))


;;; Generated autoloads from key-chord/key-chord.el

(defvar key-chord-mode nil
"Non-nil if Key-Chord mode is enabled.
See the `key-chord-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `key-chord-mode'.")
(custom-autoload 'key-chord-mode "key-chord/key-chord" nil)
(autoload 'key-chord-mode "key-chord/key-chord"
"Map pairs of simultaneously pressed keys to commands.

See functions `key-chord-define-global', `key-chord-define-local',
and `key-chord-define' and variables `key-chord-two-keys-delay'
and `key-chord-one-key-delay'.

This is a global minor mode.  If called interactively, toggle the
`Key-Chord mode' mode.  If the prefix argument is positive, enable the
mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='key-chord-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'key-chord-define-global "key-chord/key-chord"
"Define a key-chord of the two keys in KEYS starting a COMMAND.

KEYS can be a string or a vector of two elements. Currently only
elements that corresponds to ascii codes in the range 32 to 126
can be used.

COMMAND can be an interactive function, a string, or nil.
If COMMAND is nil, the key-chord is removed.

Note that KEYS defined locally in the current buffer will have
precedence.

(fn KEYS COMMAND)" t)
(autoload 'key-chord-define-local "key-chord/key-chord"
"Locally define a key-chord of the two keys in KEYS starting a COMMAND.

KEYS can be a string or a vector of two elements. Currently only
elements that corresponds to ascii codes in the range 32 to 126
can be used.

COMMAND can be an interactive function, a string, or nil.
If COMMAND is nil, the key-chord is removed.

The binding goes in the current buffer's local map, which in most
cases is shared with all other buffers in the same major mode.

(fn KEYS COMMAND)" t)
(autoload 'key-chord-register-keys "key-chord/key-chord"
"Register KEY1 and KEY2 as being used in a key chord.
This function should be called by packages that define key chords
outside of the standard key-chord-define functions.

(fn KEY1 KEY2)")
(autoload 'key-chord-unregister-keys "key-chord/key-chord"
"Unregister KEY1 and KEY2 as being used in a key chord.
This should only be called if you're certain these keys are not
used in any other chords.

(fn KEY1 KEY2)")
(autoload 'key-chord-define "key-chord/key-chord"
"Define in KEYMAP, a key-chord of the two keys in KEYS starting a COMMAND.

KEYS can be a string or a vector of two elements. Currently only
elements that corresponds to ascii codes in the range 32 to 126
can be used.

COMMAND can be an interactive function, a string, or nil.
If COMMAND is nil, the key-chord is removed.

(fn KEYMAP KEYS COMMAND)")
(register-definition-prefixes "key-chord/key-chord" '("key-chord-"))


;;; Generated autoloads from my-c++-mode.el

(autoload 'my/c++-mode-hook "my-c++-mode"
"Custom C++ mode hook.")
(register-definition-prefixes "my-c++-mode" '("c++-mode-abbrev-table" "my/"))


;;; Generated autoloads from my-c-mode.el

(register-definition-prefixes "my-c-mode" '("my/c-"))


;;; Generated autoloads from my-c-mode-common.el

(register-definition-prefixes "my-c-mode-common" '("my/" "view-qt-doc"))


;;; Generated autoloads from my-cc-block-comment.el

(register-definition-prefixes "my-cc-block-comment" '("my/cc-"))


;;; Generated autoloads from my-cmake-mode.el

(register-definition-prefixes "my-cmake-mode" '("cmake-mode-abbrev-table" "my/cmake-"))


;;; Generated autoloads from my-constants.el

(register-definition-prefixes "my-constants" '("my/"))


;;; Generated autoloads from my-customizations.el

(register-definition-prefixes "my-customizations" '("my/"))


;;; Generated autoloads from my-dired-mode.el

(register-definition-prefixes "my-dired-mode" '("my/"))


;;; Generated autoloads from my-env.el

(register-definition-prefixes "my-env" '("my/"))


;;; Generated autoloads from my-find-known-bindings.el

(register-definition-prefixes "my-find-known-bindings" '("my/find-known-bindings"))


;;; Generated autoloads from my-fontify-braces.el

(register-definition-prefixes "my-fontify-braces" '("my/fontify-braces"))


;;; Generated autoloads from my-functions.el

(register-definition-prefixes "my-functions" '("my/" "tempo-template-my/org-emacs-lisp-source"))


;;; Generated autoloads from my-insert-block-comment.el

(register-definition-prefixes "my-insert-block-comment" '("my/insert-block-comment"))


;;; Generated autoloads from my-js2-mode.el

(register-definition-prefixes "my-js2-mode" '("my/js2-mode-hook"))


;;; Generated autoloads from my-json-mode.el

(register-definition-prefixes "my-json-mode" '("my/json-mode-hook"))


;;; Generated autoloads from my-ksh-mode.el

(register-definition-prefixes "my-ksh-mode" '("my/ksh-"))


;;; Generated autoloads from my-layout.el

(register-definition-prefixes "my-layout" '("my/layout-"))


;;; Generated autoloads from my-lisp-mode.el

(register-definition-prefixes "my-lisp-mode" '("my/"))


;;; Generated autoloads from my-makefile-mode.el

(register-definition-prefixes "my-makefile-mode" '("my/makefile-"))


;;; Generated autoloads from my-markdown-mode.el

(register-definition-prefixes "my-markdown-mode" '("my/"))


;;; Generated autoloads from my-modes.el

(register-definition-prefixes "my-modes" '("my/"))


;;; Generated autoloads from my-python-mode.el

(register-definition-prefixes "my-python-mode" '("my/"))


;;; Generated autoloads from my-sh-mode.el

(register-definition-prefixes "my-sh-mode" '("my/sh-"))


;;; Generated autoloads from my-shell-mode.el

(register-definition-prefixes "my-shell-mode" '("my/"))


;;; Generated autoloads from my-swift-mode.el

(register-definition-prefixes "my-swift-mode" '("my/swift-mode-hook"))


;;; Generated autoloads from native-complete.el

(autoload 'native-complete-setup-bash "native-complete"
"Setup support for native-complete enabled bash shells.
This involves not sending the `--noediting' argument as well as
setting `TERM' to a value other then dumb." t)
(autoload 'native-complete-at-point "native-complete"
"Get the candidates from the underlying shell.
This should behave the same as sending TAB in an terminal
emulator.")
(autoload 'native-complete-check-config "native-complete"
"Check the setup of native complete and look for common problems." t)
(register-definition-prefixes "native-complete" '("native-complete-"))


;;; End of scraped data

(provide '.user-lisp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; .user-lisp-autoloads.el ends here
