;; (defun my-color-map ()
;;   (interactive)
;;   (list-colors-display)
;;   (with-current-buffer (get-buffer "*Colors*")
;;     (while (looking-at "^[A-Za-z0-9 ]+")
;;       (let* ((name (buffer-substring-no-properties (match-beginning 0)
;; 						   (match-end 0)))
;; 	     (rgb (assoc name win32-color-map)))
;; 	(when rgb
;; 	  (setq rgb (cdr rgb))
;; 	  (end-of-line)
;; 	  (insert " " (format "%02x" (logand rgb 255))
;; 		  " " (format "%02x" (logand (lsh rgb -8) 255))
;; 		  " " (format "%02x" (logand (lsh rgb -16) 255))))
;; 	(beginning-of-line 2)))))
